# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

variables:
  - group: ifp-keystore-secrets
  - name: Flutter.Version
    value: "3.3.10"
  - name: Flutter.Url
    value: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_$(Flutter.Version)-stable.zip
  - name: Flutter.Bin
    value: $(Pipeline.Workspace)/flutter/flutter/bin/flutter
  - name: GRADLE_USER_HOME
    value: $(Pipeline.Workspace)/.gradle
  - name: Maven.Settings
    value: /Users/runner/.m2/settings.xml
    #value: $env:USERPROFILE\.m2\settings.xml
pool:
  vmImage: "macOS-12"

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"

  - script: curl $(Flutter.Url) --output $(Pipeline.Workspace)/flutter.zip
    displayName: Download the flutter SDK

  - task: ExtractFiles@1
    displayName: Extract the flutter SDK
    inputs:
      archiveFilePatterns: "$(Pipeline.Workspace)/flutter.zip"
      destinationFolder: "$(Pipeline.Workspace)/flutter"

  - task: MavenAuthenticate@0
    displayName: "Provides maven credentials for Azure Artifacts"
    inputs:
      artifactsFeeds: "myViewBoard_Artifacts"

  - task: PowerShell@2
    displayName: Extract the credentials of Azure Artifacts
    inputs:
      targetType: "inline"
      script: |
        [xml]$doc = Get-Content -path $(Maven.Settings)
        $username=$doc.settings.servers.server.username
        $password=$doc.settings.servers.server.password
        Write-Host "##vso[task.setvariable variable=artifacts.username]$username"
        Write-Host "##vso[task.setvariable variable=artifacts.password;issecret=true]$password"

  - task: Cache@2
    displayName: Configure Gradle caching
    enabled: "true"
    inputs:
      key: 'gradle | "$(Agent.OS)" | android/build.gradle, example/android/app/build.gradle, example/android/build.gradle'
      restoreKeys: |
        gradle | "$(Agent.OS)"
        gradle
      path: $(GRADLE_USER_HOME)

  - script: $(Flutter.Bin) build apk
    displayName: Build the plugin and the example App
    workingDirectory: "$(Build.SourcesDirectory)/example"
    env:
      GRADLE_OPTS: "-Dorg.gradle.caching=true"
      ORG_GRADLE_PROJECT_AZURE_ARTIFACTS_USERNAME: $(artifacts.username)
      ORG_GRADLE_PROJECT_AZURE_ARTIFACTS_PASSWORD: $(artifacts.password)

  - script: ./gradlew --stop
    displayName: Stop Gradle daemon
    workingDirectory: "$(Build.SourcesDirectory)/example/android"

  - task: AndroidSigning@3
    inputs:
      apkFiles: "**/*.apk"
      apksign: true
      apksignerKeystoreFile: "ifp.keystore"
      apksignerKeystorePassword: "$(keystore.password)"
      apksignerKeystoreAlias: "$(keystore.alias)"
      apksignerKeyPassword: "$(key.password)"
      zipalign: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/example/build/app/outputs/flutter-apk/"
      contents: "**"
      targetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
