trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
      - hotfix/*

pool:
  name: "AirSync macOS Pool"

variables:
  - name: Flutter.Bin
    value: fvm flutter

jobs:
  - job: Build
    strategy:
      matrix:
        openproduction:
          flavor: "open-production"
          buildOptions: "--flavor openproduction -t lib/main_production.dart"
    steps:
      - checkout: self
        persistCredentials: "true"
        lfs: "true"

      - task: PowerShell@2
        displayName: Authenticates git repos
        inputs:
          targetType: "inline"
          script: |
            $header = "AUTHORIZATION: bearer $(System.AccessToken)"
            git config --global http.https://viewsonic-ssi.visualstudio.com/Display%20App/.extraheader $header

      - task: MavenAuthenticate@0
        displayName: "Provides maven credentials for Azure Artifacts"
        inputs:
          artifactsFeeds: "myViewBoard_Artifacts"

      - task: PowerShell@2
        displayName: Extract the credentials of Azure Artifacts
        inputs:
          targetType: "inline"
          script: |
            [xml]$doc = Get-Content -path ~/.m2/settings.xml
            $username=$doc.settings.servers.server.username
            $password=$doc.settings.servers.server.password
            Write-Host "##vso[task.setvariable variable=artifacts.username]$username"
            Write-Host "##vso[task.setvariable variable=artifacts.password;issecret=true]$password"

      - script: |
          # Ensure git config is available in this shell session
          git config --global http.https://viewsonic-ssi.visualstudio.com/Display%20App/.extraheader "AUTHORIZATION: bearer $(System.AccessToken)"

          # Download packages
          $(Flutter.Bin) pub get
        displayName: Download packages
        workingDirectory: "$(Build.SourcesDirectory)"

      # lint
      - script: $(Flutter.Bin) analyze --no-pub --no-fatal-infos
        displayName: Run lint checks
        workingDirectory: "$(Build.SourcesDirectory)"

      # test
      - script: $(Flutter.Bin) test -j 4 --no-pub --coverage --branch-coverage
        displayName: Run test
        workingDirectory: "$(Build.SourcesDirectory)"

      - script: $(Flutter.Bin) build apk $(buildOptions)
        displayName: Build App
        workingDirectory: "$(Build.SourcesDirectory)"
        env:
          ORG_GRADLE_PROJECT_AZURE_ARTIFACTS_USERNAME: $(artifacts.username)
          ORG_GRADLE_PROJECT_AZURE_ARTIFACTS_PASSWORD: $(artifacts.password)
