trigger: none
pr: none

pool:
  name: "AirSync macOS Pool"

variables:
  - name: Flutter.Bin
    value: fvm flutter
  - name: GRADLE_OPTS
    value: "-Dorg.gradle.jvmargs=-Xmx5g"
  - name: Flutter.Verbose
    value: ""
  - name: Flutter.Build.Options
    value: "--no-pub --obfuscate --split-debug-info=debug_info/"
  - name: Signing.Arguments
    value: "--min-sdk-version 21"
  - group: "ifp-keystore-secrets"
  - group: "store-keystore-secrets"
  - group: "sentry-airsync-receiver"

jobs:
  - job: Build
    strategy:
      maxParallel: 4
      matrix:
        edlaStage:
          flavor: "edlaStage"
          channel: "edla"
          target: "stage"
          appFileExt: '.apk'
          signingConfig: "ifp"
          splitPerAbi: true

        edlaProduction:
          flavor: "edlaProduction"
          channel: "edla"
          target: "production"
          appFileExt: '.apk'
          signingConfig: "ifp"
          splitPerAbi: true

        ifpStage:
          flavor: "ifpStage"
          channel: "ifp"
          target: "stage"
          appFileExt: '.apk'
          signingConfig: "ifp"
          splitPerAbi: true

        ifpProduction:
          flavor: "ifpProduction"
          channel: "ifp"
          target: "production"
          appFileExt: '.apk'
          signingConfig: "ifp"
          splitPerAbi: true

        openStage:
          flavor: "openStage"
          channel: "open"
          target: "stage"
          appFileExt: '.apk'
          signingConfig: "store"

        openProduction:
          flavor: "openProduction"
          channel: "open"
          target: "production"
          appFileExt: '.apk'
          signingConfig: "store"

        storeStage:
          flavor: "storeStage"
          channel: "store"
          target: "stage"
          appFileExt: '.aab'
          signingConfig: "store"
          appbundle: true

        storeProduction:
          flavor: "storeProduction"
          channel: "store"
          target: "production"
          appFileExt: '.aab'
          signingConfig: "store"
          appbundle: true
    steps:
      - checkout: self
        fetchDepth: 1
        fetchTags: "false"
        persistCredentials: "true"

      - task: PowerShell@2
        displayName: Authenticates git repos
        inputs:
          targetType: "inline"
          script: |
            $header = "AUTHORIZATION: bearer $(System.AccessToken)"
            git config --global http.https://viewsonic-ssi.visualstudio.com/Display%20App/.extraheader $header

      - task: MavenAuthenticate@0
        displayName: "Provides maven credentials for Azure Artifacts"
        inputs:
          artifactsFeeds: "myViewBoard_Artifacts"

      - task: PowerShell@2
        displayName: Extract the credentials of Azure Artifacts
        inputs:
          targetType: "inline"
          script: |
            [xml]$doc = Get-Content -path ~/.m2/settings.xml
            $username=$doc.settings.servers.server.username
            $password=$doc.settings.servers.server.password
            Write-Host "##vso[task.setvariable variable=ORG_GRADLE_PROJECT_AZURE_ARTIFACTS_USERNAME]$username"
            Write-Host "##vso[task.setvariable variable=ORG_GRADLE_PROJECT_AZURE_ARTIFACTS_PASSWORD]$password"

      - script: $(Flutter.Bin) pub get
        displayName: Download packages


      # Build Single APK
      - script: $(Flutter.Bin) $(Flutter.Verbose) build apk --flavor $(flavor) -t lib/main_$(target).dart $(Flutter.Build.Options)
        displayName: Build Single APK
        condition: ne(variables['appbundle'], true)

      # Build Split APK
      - script: $(Flutter.Bin) $(Flutter.Verbose) build apk --flavor $(flavor) -t lib/main_$(target).dart $(Flutter.Build.Options) --split-per-abi
        displayName: Build Split APK
        condition: eq(variables['splitPerAbi'], true)

      # Build App bundle
      - script: $(Flutter.Bin) $(Flutter.Verbose) build appbundle --flavor $(flavor) -t lib/main_$(target).dart $(Flutter.Build.Options)
        displayName: Build App Bundle
        condition: eq(variables['appbundle'], true)


      # Uploading debug symbols
      - script: $(Flutter.Bin) packages pub run sentry_dart_plugin
        displayName: Uploading debug symbols
        enabled: "false"

      - task: AndroidSigning@3
        displayName: Sign App - ifp
        condition: eq(variables['signingConfig'], 'ifp')
        inputs:
          apkFiles: '$(Build.SourcesDirectory)/build/app/outputs/**/*$(appFileExt)'
          keystoreFile: ifp.keystore
          keystorePass: $(ifp.keystore.password)
          keystoreAlias: $(ifp.keystore.alias)
          keyPass: '$(ifp.key.password)'
          apksignerArguments: $(Signing.Arguments)

      - task: AndroidSigning@3
        displayName: Sign App - store
        condition: eq(variables['signingConfig'], 'store')
        inputs:
          apkFiles: '$(Build.SourcesDirectory)/build/app/outputs/**/*$(appFileExt)'
          keystoreFile: store.keystore
          keystorePass: $(store.keystore.password)
          keystoreAlias: $(store.keystore.alias)
          keyPass: '$(store.key.password)'
          apksignerArguments: $(Signing.Arguments)

      # Prepare to publish
      - task: CopyFiles@2
        displayName: Copy artifacts
        inputs:
          flattenFolders: true
          contents: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/**/*.aab

          targetFolder: "$(Build.ArtifactStagingDirectory)/$(channel)"

      # Rename single APK
      - task: PowerShell@2
        displayName: Rename Single
        condition: ne(variables['appbundle'], true)
        inputs:
          filePath: "ci/scripts/rename.ps1"
          arguments: -Wd $(Build.ArtifactStagingDirectory)/$(channel) -Channel $(channel) -Target $(target) -Single

      # Rename split APKs
      - task: PowerShell@2
        displayName: Rename Split
        condition: eq(variables['splitPerAbi'], true)
        inputs:
          filePath: "ci/scripts/rename.ps1"
          arguments: -Wd $(Build.ArtifactStagingDirectory)/$(channel) -Channel $(channel) -Target $(target) -Split

      # Rename bundle
      - task: PowerShell@2
        displayName: Rename App Bundle
        condition: eq(variables['appbundle'], true)
        inputs:
          filePath: "ci/scripts/rename.ps1"
          arguments: -Wd $(Build.ArtifactStagingDirectory)/$(channel) -Channel $(channel) -Target $(target) -Bundle

      # Publish artifacts
      - task: PublishBuildArtifacts@1
        displayName: Publish build
        inputs:
          pathToPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "$(target)"
          Parallel: true