# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: macos-latest

steps:
  - checkout: self

  - script: |
      chmod +x script/generate_certs.sh
      ./script/generate_certs.sh 20250201 20260201
    displayName: 'Generate webtransport certs'
