// Mocks generated by Mockito 5.4.4 from annotations
// in display_flutter/test/rtc_stats_parse_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:display_flutter/model/rtc_stats.dart' as _i3;
import 'package:display_flutter/model/rtc_stats_reporter.dart' as _i2;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RtcStatsReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockRtcStatsReporter extends _i1.Mock implements _i2.RtcStatsReporter {
  MockRtcStatsReporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void videoInboundStats(_i3.RtcVideoInboundStats? stats) => super.noSuchMethod(
        Invocation.method(
          #videoInboundStats,
          [stats],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pairCandidates(
    _i4.StatsReport? localCandidateReport,
    _i4.StatsReport? remoteCandidateReport,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pairCandidates,
          [
            localCandidateReport,
            remoteCandidateReport,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectedCandidatePair(_i4.StatsReport? selectedCandidatePair) =>
      super.noSuchMethod(
        Invocation.method(
          #selectedCandidatePair,
          [selectedCandidatePair],
        ),
        returnValueForMissingStub: null,
      );
}
