// Mocks generated by Mockito 5.4.4 from annotations
// in display_flutter/test/rtc_stats_parse_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:display_flutter/model/rtc_stats.dart' as _i3;
import 'package:display_flutter/model/rtc_stats_presenter.dart' as _i5;
import 'package:display_flutter/model/rtc_stats_reporter.dart' as _i2;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RtcStatsReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockRtcStatsReporter extends _i1.Mock implements _i2.RtcStatsReporter {
  MockRtcStatsReporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void updateVideoInboundStats(_i3.RtcVideoInboundStats? stats) =>
      super.noSuchMethod(
        Invocation.method(
          #updateVideoStats,
          [stats],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pairCandidates(
    _i4.StatsReport? localCandidateReport,
    _i4.StatsReport? remoteCandidateReport,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pairCandidates,
          [
            localCandidateReport,
            remoteCandidateReport,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectedCandidatePair(_i4.StatsReport? selectedCandidatePair) =>
      super.noSuchMethod(
        Invocation.method(
          #selectedCandidatePair,
          [selectedCandidatePair],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCandidatePairStats(_i4.StatsReport? report) => super.noSuchMethod(
        Invocation.method(
          #updateCandidatePairStats,
          [report],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCodecStats(_i4.StatsReport? report) => super.noSuchMethod(
        Invocation.method(
          #updateCodecStats,
          [report],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateLocalCandidate(List<_i4.StatsReport>? reports) =>
      super.noSuchMethod(
        Invocation.method(
          #updateLocalCandidate,
          [reports],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRemoteCandidate(List<_i4.StatsReport>? reports) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRemoteCandidate,
          [reports],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RtcStatsPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockRtcStatsPresenter extends _i1.Mock implements _i5.RtcStatsPresenter {
  MockRtcStatsPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onVideoInboundStatsPresent(
          dynamic Function(List<_i3.RtcVideoInboundStats>)?
              _onVideoStatsPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onVideoStatsPresent,
          _onVideoStatsPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onLocalCandidatesPresent(
          dynamic Function(Map<String, _i3.RtcIceCandidate>)?
              _onLocalCandidatesPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onLocalCandidatesPresent,
          _onLocalCandidatesPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoteCandidatesPresent(
          dynamic Function(Map<String, _i3.RtcIceCandidate>)?
              _onRemoteCandidatesPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onRemoteCandidatesPresent,
          _onRemoteCandidatesPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onCandidatePairPresent(
          dynamic Function(Map<String, _i3.RtcIceCandidatePairStats>)?
              _onCandidatePairPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onCandidatePairPresent,
          _onCandidatePairPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onCodecStatsPresent(
          dynamic Function(Map<String, _i3.RtcCodecStats>)?
              _onCodecStatsPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onCodecStatsPresent,
          _onCodecStatsPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onLocalSDPPresent(
          dynamic Function(_i4.RTCSessionDescription)? _onLocalSDPPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onLocalSDPPresent,
          _onLocalSDPPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoteSDPPresent(
          dynamic Function(_i4.RTCSessionDescription)? _onRemoteSDPPresent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onRemoteSDPPresent,
          _onRemoteSDPPresent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateVideoInboundStats(_i3.RtcVideoInboundStats? stats) =>
      super.noSuchMethod(
        Invocation.method(
          #updateVideoStats,
          [stats],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateLocalCandidate(List<_i4.StatsReport>? reports) =>
      super.noSuchMethod(
        Invocation.method(
          #updateLocalCandidate,
          [reports],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRemoteCandidate(List<_i4.StatsReport>? reports) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRemoteCandidate,
          [reports],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCandidatePairStats(_i4.StatsReport? report) => super.noSuchMethod(
        Invocation.method(
          #updateCandidatePairStats,
          [report],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCodecStats(_i4.StatsReport? report) => super.noSuchMethod(
        Invocation.method(
          #updateCodecStats,
          [report],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLocalSDP(_i4.RTCSessionDescription? sdp) => super.noSuchMethod(
        Invocation.method(
          #setLocalSDP,
          [sdp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRemoteSDP(_i4.RTCSessionDescription? sdp) => super.noSuchMethod(
        Invocation.method(
          #setRemoteSDP,
          [sdp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pairCandidates(
    _i4.StatsReport? localCandidateReport,
    _i4.StatsReport? remoteCandidateReport,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pairCandidates,
          [
            localCandidateReport,
            remoteCandidateReport,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectedCandidatePair(_i4.StatsReport? selectedCandidatePair) =>
      super.noSuchMethod(
        Invocation.method(
          #selectedCandidatePair,
          [selectedCandidatePair],
        ),
        returnValueForMissingStub: null,
      );
}
