trigger:
  batch: true
  branches:
    include:
      - main
      - HotFix/*

pool:
  vmImage: macOS-latest

variables:
  - name: Flutter.Version
    value: "3.24.2"
  - name: Flutter.Bin
    value: $(Pipeline.Workspace)/flutter/flutter/bin/flutter
  - name: FlutterSdkPlatform
    value: "macos"
  - name: PUB_CACHE
    value: $(Pipeline.Workspace)/.pub-cache
  - name: Dart.Bin
    value: $(Pipeline.Workspace)/flutter/flutter/bin/dart

jobs:
  - job: Build
    strategy:
      matrix:
        dev:
          flavor: 'dev'
          buildOptions: '-t ./lib/main_dev.dart --source-maps --pwa-strategy=none'
#        stage:
#          flavor: 'stage'
#          buildOptions: '--release -t ./lib/main_stage.dart --source-maps --pwa-strategy=none'
#        prod:
#          flavor: 'prod'
#          buildOptions: '--release -t ./lib/main_production.dart --source-maps --pwa-strategy=none'

    pool:
      vmImage: macOS-latest

    steps:
      - checkout: self
        persistCredentials: "true"
        lfs: "true"

      - task: PowerShell@2
        displayName: Authenticates git repos
        inputs:
          targetType: 'inline'
          script: |
            $header = "AUTHORIZATION: bearer $(System.AccessToken)"
            git config --global http.https://viewsonic-ssi.visualstudio.com/Display%20App/.extraheader $header

      - task: Cache@2
        displayName: Configure flutter caching
        enabled: false
        inputs:
          key: 'pubspec | "$(Agent.OS)" | pubspec.yaml, pubspec.lock'
          restoreKeys: |
            pubspec | "$(Agent.OS)"
            pubspec
          path: $(PUB_CACHE)

      # install flutter SDK
      - script: curl https://storage.googleapis.com/flutter_infra_release/releases/stable/$(FlutterSdkPlatform)/flutter_$(FlutterSdkPlatform)_$(Flutter.Version)-stable.zip --output $(Pipeline.Workspace)/flutter.zip
        displayName: Download the flutter SDK

      - task: ExtractFiles@1
        displayName: Extract the flutter SDK
        inputs:
          archiveFilePatterns: "$(Pipeline.Workspace)/flutter.zip"
          destinationFolder: "$(Pipeline.Workspace)/flutter"

      - script: $(Flutter.Bin) config --enable-web
        displayName: Enable Flutter for web
        workingDirectory: "$(Build.SourcesDirectory)"

      - script: $(Flutter.Bin) analyze --no-fatal-infos
        enabled: false
        displayName: Run lint checks
        workingDirectory: "$(Build.SourcesDirectory)"

      # Verify Dart
      - script: |
          echo "Flutter bin location: $(Flutter.Bin)"
          echo "Dart bin location: $(Dart.Bin)"
          $(Dart.Bin) --version
        displayName: Verify Dart installation

      # Build
      - script: $(Flutter.Bin) build web $(buildOptions)
        displayName: Build

      # Overwrite service-worker RESOURCES
      - script: $(Dart.Bin) $(Build.SourcesDirectory)/web/generate_assets.dart
        displayName: Generate resources list

      # Prepare to publish
      - task: CopyFiles@2
        displayName: Copy artifacts
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/build/web"
          contents: |
            **
            !**/*.js.map
          targetFolder: "$(Build.ArtifactStagingDirectory)"

      # Publish artifacts
      - task: PublishBuildArtifacts@1
        displayName: Publish build
        inputs:
          pathToPublish: "$(Build.ArtifactStagingDirectory)"
          artifactName: $(flavor)
          Parallel: true