trigger:
  batch: true
  branches:
    include:
      - main
      - HotFix/*

pool:
  name: "AirSync macOS Pool"

variables:
  - name: Flutter.Bin
    value: fvm flutter
  - name: Dart.Bin
    value: fvm dart

jobs:
  - job: Build
    strategy:
      matrix:
        dev:
          flavor: 'dev'
          buildOptions: '-t ./lib/main_dev.dart --source-maps --pwa-strategy=none'
        stage:
          flavor: 'stage'
          buildOptions: '--release -t ./lib/main_stage.dart --source-maps --pwa-strategy=none'
        prod:
          flavor: 'prod'
          buildOptions: '--release -t ./lib/main_production.dart --source-maps --pwa-strategy=none'

    steps:
      - checkout: self
        persistCredentials: "true"
        lfs: "true"

      - task: PowerShell@2
        displayName: Authenticates git repos
        inputs:
          targetType: 'inline'
          script: |
            $header = "AUTHORIZATION: bearer $(System.AccessToken)"
            git config --global http.https://viewsonic-ssi.visualstudio.com/Display%20App/.extraheader $header

      - script: $(Flutter.Bin) pub get
        displayName: Download packages

      - script: $(Flutter.Bin) analyze --no-pub --no-fatal-infos
        enabled: false
        displayName: Run lint checks

      # Build
      - script: $(Flutter.Bin) build web --no-pub $(buildOptions)
        displayName: Build

      # Overwrite service-worker RESOURCES
      - script: $(Dart.Bin) $(Build.SourcesDirectory)/web/generate_assets.dart
        displayName: Generate resources list

      # Prepare to publish
      - task: CopyFiles@2
        displayName: Copy artifacts
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/build/web"
          contents: |
            **
            !**/*.js.map
          targetFolder: "$(Build.ArtifactStagingDirectory)"

      - task: PublishPipelineArtifact@1
        displayName: Publish Build Artifact
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)"
          artifact: $(flavor)