trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main
        - HotFix/*

variables:
  - name: Flutter.Bin
    value: fvm flutter

jobs:
  - job: Build
    strategy:
      matrix:
        # mac:
        #   poolName: "AirSync macOS Pool"
        #   platform: 'mac'
        #   buildCommand: 'macos'
        #   extraBuildOptions: ''
        windows:
          poolName: "AirSync Windows Pool"
          platform: "windows"
          buildCommand: "windows"
          extraBuildOptions: ""
        web:
          poolName: "AirSync macOS Pool"
          platform: "web"
          buildCommand: "web"
          extraBuildOptions: ""
        android:
          poolName: "AirSync macOS Pool"
          platform: "android"
          buildCommand: "apk"
          extraBuildOptions: ""
        #ios:
        #  poolName: 'macOS-latest'
        #  buildCommand: ''
        #  extraBuildOptions: '--flavor ifp'
    pool:
      name: $(poolName)

    steps:
      - checkout: self
        persistCredentials: "true"
        lfs: "true"

      - task: PowerShell@2
        displayName: Authenticates git repos
        inputs:
          targetType: "inline"
          script: |
            $header = "AUTHORIZATION: bearer $(System.AccessToken)"
            git config --global http.https://viewsonic-ssi.visualstudio.com/Display%20App/.extraheader $header

      - script: $(Flutter.Bin) pub get
        displayName: Download packages
        workingDirectory: "$(Build.SourcesDirectory)"

      # lint
      - script: $(Flutter.Bin) analyze --no-pub --no-fatal-infos
        displayName: Run lint checks
        workingDirectory: "$(Build.SourcesDirectory)"

      # build prod
      - script: $(Flutter.Bin) build $(buildCommand) --no-pub $(extraBuildOptions) -t ./lib/main_production.dart
        displayName: Build prod
