// Mocks generated by Mockito 5.4.4 from annotations
// in display_cast_flutter/test/app_amplify_firehose_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:amplify_flutter/amplify_flutter.dart' as _i4;
import 'package:display_cast_flutter/utilities/app_amplify_firehose.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirehoseHttpResponse_0 extends _i1.SmartFake
    implements _i2.FirehoseHttpResponse {
  _FakeFirehoseHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirehoseHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirehoseHttpClient extends _i1.Mock
    implements _i2.FirehoseHttpClient {
  MockFirehoseHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.FirehoseHttpResponse> send(_i4.AWSBaseHttpRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue: _i3.Future<_i2.FirehoseHttpResponse>.value(
            _FakeFirehoseHttpResponse_0(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FirehoseHttpResponse>);
}

/// A class which mocks [FirehoseRequestSigner].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirehoseRequestSigner extends _i1.Mock
    implements _i2.FirehoseRequestSigner {
  MockFirehoseRequestSigner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AWSBaseHttpRequest> sign(
    _i4.AWSHttpRequest? request, {
    required String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [request],
          {#region: region},
        ),
        returnValue: _i3.Future<_i4.AWSBaseHttpRequest>.value(
            _i5.dummyValue<_i4.AWSBaseHttpRequest>(
          this,
          Invocation.method(
            #sign,
            [request],
            {#region: region},
          ),
        )),
      ) as _i3.Future<_i4.AWSBaseHttpRequest>);
}

/// A class which mocks [ConnectivityMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityMonitor extends _i1.Mock
    implements _i2.ConnectivityMonitor {
  MockConnectivityMonitor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<bool> get onConnectivityChanged => (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
